name: CI Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: personal-gh

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Print hello world
        run: echo "¡El runner está funcionando!"