name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Load NVM, set Node.js and install Yarn
        run: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

          nvm install 16
          nvm use 16

          npm install -g yarn
          
          yarn install
          yarn build
        shell: bash

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
